import { ApiKeyScope, ApiKeyRole } from '@/interfaces/api-key.interface';

export const API_KEY_SCOPE_LABELS: Record<ApiKeyScope, string> = {
  'menu:read': 'Menu — Read',
  'menu:write': 'Menu — Write',
  'orders:read': 'Orders — Read',
  'orders:write': 'Orders — Write',
  'inventory:read': 'Inventory — Read',
  'inventory:write': 'Inventory — Write',
  'customers:read': 'Customers — Read',
  'customers:write': 'Customers — Write',
  'payments:read': 'Payments — Read',
  'payments:write': 'Payments — Write',
  'tabs:read': 'Tabs — Read',
  'tabs:write': 'Tabs — Write',
  'rewards:read': 'Rewards — Read',
  'settings:read': 'Settings — Read',
  'settings:write': 'Settings — Write',
  'analytics:read': 'Analytics — Read',
  'audit:read': 'Audit Logs — Read',
};

export const API_KEY_ROLE_SCOPES: Record<ApiKeyRole, ApiKeyScope[]> = {
  customer: [
    'menu:read',
    'orders:read',
    'orders:write',
    'payments:read',
    'payments:write',
    'rewards:read',
    'tabs:read',
  ],
  csr: [
    'menu:read',
    'orders:read',
    'orders:write',
    'customers:read',
    'customers:write',
    'payments:read',
    'payments:write',
    'rewards:read',
    'tabs:read',
    'tabs:write',
  ],
  admin: [
    'menu:read',
    'menu:write',
    'orders:read',
    'orders:write',
    'customers:read',
    'customers:write',
    'payments:read',
    'payments:write',
    'rewards:read',
    'tabs:read',
    'tabs:write',
    'inventory:read',
    'analytics:read',
    'audit:read',
  ],
  'super-admin': [
    'menu:read',
    'menu:write',
    'orders:read',
    'orders:write',
    'inventory:read',
    'inventory:write',
    'customers:read',
    'customers:write',
    'payments:read',
    'payments:write',
    'tabs:read',
    'tabs:write',
    'rewards:read',
    'settings:read',
    'settings:write',
    'analytics:read',
    'audit:read',
  ],
  // REQ-034: bar / waiting are csr-equivalent for API scopes too;
  // kitchen scopes are deliberately limited (no order / payment writes).
  bar: [
    'menu:read',
    'orders:read',
    'orders:write',
    'customers:read',
    'customers:write',
    'payments:read',
    'payments:write',
    'rewards:read',
    'tabs:read',
    'tabs:write',
  ],
  waiting: [
    'menu:read',
    'orders:read',
    'orders:write',
    'customers:read',
    'customers:write',
    'payments:read',
    'payments:write',
    'rewards:read',
    'tabs:read',
    'tabs:write',
  ],
  kitchen: ['menu:read', 'inventory:read'],
};

export const API_KEY_ROLE_LABELS: Record<ApiKeyRole, string> = {
  customer: 'Customer',
  csr: 'Customer Service',
  admin: 'Admin',
  'super-admin': 'Super Admin',
  kitchen: 'Kitchen',
  bar: 'Bar',
  waiting: 'Waiting',
};

export const API_KEY_ROLE_DESCRIPTIONS: Record<ApiKeyRole, string> = {
  customer: 'Menu browsing, ordering, payments, and rewards',
  csr: 'Orders, customers, payments, rewards, and tab management',
  admin:
    'CSR scopes plus menu writes, inventory reads, analytics, and audit logs',
  'super-admin': 'Full access to all API scopes',
  kitchen: 'Read-only menu + inventory for recipe + production work',
  bar: 'Bar staff: csr-equivalent (orders, customers, payments, rewards, tabs)',
  waiting:
    'Waiting staff: csr-equivalent (orders, customers, payments, rewards, tabs)',
};
