import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { TrendingDown, TrendingUp } from 'lucide-react';
import type { DailySummaryReport } from '@/services/financial-report-service';

interface ProfitSectionProps { report: DailySummaryReport; }
const formatCurrency = (amount: number) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN' }).format(amount);

export function ProfitSection({ report }: ProfitSectionProps) {
  const isProfit = report.netProfit >= 0;
  const bestCategory = report.categories.reduce<typeof report.categories[number] | undefined>((best, category) => !best || category.grossProfit > best.grossProfit ? category : best, undefined);
  return <div className="space-y-6">
    <Card><CardHeader><CardTitle>Profit &amp; Loss Statement</CardTitle></CardHeader><CardContent><div className="space-y-4">
      <div className="space-y-2"><div className="flex items-center justify-between py-2"><span className="font-semibold">Total Revenue</span><span className="text-lg font-bold text-primary">{formatCurrency(report.revenue.totalRevenue)}</span></div><div className="space-y-1 pl-4 text-sm">{report.categories.map((category) => <div key={category.slug} className="flex justify-between text-muted-foreground"><span>- {category.label} Revenue</span><span>{formatCurrency(category.revenue.totalRevenue)}</span></div>)}</div></div>
      <div className="border-t pt-2"><div className="flex items-center justify-between py-2"><span className="font-semibold">Less: Cost of Goods Sold</span><span className="text-lg font-bold text-orange-600">({formatCurrency(report.costs.totalDirectCosts)})</span></div><div className="space-y-1 pl-4 text-sm">{report.categories.map((category) => <div key={category.slug} className="flex justify-between text-muted-foreground"><span>- {category.label} Costs</span><span>({formatCurrency(category.costs.totalCost)})</span></div>)}</div></div>
      <div className="-mx-6 border-t-2 border-green-500 bg-green-50 px-6 py-3 dark:bg-green-950"><div className="flex items-center justify-between"><div><span className="text-lg font-bold">Gross Profit</span><div className="text-sm text-muted-foreground">{report.metrics.grossProfitMargin.toFixed(1)}% margin</div></div><span className="text-2xl font-bold text-green-600">{formatCurrency(report.grossProfit.total)}</span></div></div>
      <div className="border-t pt-2"><div className="flex items-center justify-between py-2"><span className="font-semibold">Less: Operating Overhead</span><span className="text-lg font-bold text-red-600">({formatCurrency(report.operatingExpenses.totalOperatingExpenses)})</span></div><div className="pl-4 text-sm text-muted-foreground">Includes rent, salaries, utilities, and maintenance.</div></div>
      <div className={`-mx-6 border-t-2 px-6 py-4 ${isProfit ? 'border-green-500 bg-green-50 dark:bg-green-950' : 'border-red-500 bg-red-50 dark:bg-red-950'}`}><div className="flex items-center justify-between"><div className="flex items-center gap-2">{isProfit ? <TrendingUp className="h-6 w-6 text-green-600" /> : <TrendingDown className="h-6 w-6 text-red-600" />}<div><span className="text-xl font-bold">{isProfit ? 'Net Profit' : 'Net Loss'}</span><div className="text-sm text-muted-foreground">{report.metrics.netProfitMargin.toFixed(1)}% margin</div></div></div><span className={`text-3xl font-bold ${isProfit ? 'text-green-600' : 'text-red-600'}`}>{formatCurrency(Math.abs(report.netProfit))}</span></div></div>
    </div></CardContent></Card>
    <div className="grid gap-4 md:grid-cols-2">{report.categories.map((category) => <Card key={category.slug}><CardHeader><CardTitle className="text-lg">{category.label} Category Performance</CardTitle></CardHeader><CardContent><div className="space-y-3"><div className="flex justify-between"><span className="text-sm text-muted-foreground">Revenue</span><span className="font-semibold">{formatCurrency(category.revenue.totalRevenue)}</span></div><div className="flex justify-between"><span className="text-sm text-muted-foreground">Cost</span><span className="font-semibold">({formatCurrency(category.costs.totalCost)})</span></div><div className="border-t pt-2"><div className="flex items-center justify-between"><span className="font-bold">Gross Profit</span><span className="text-lg font-bold text-green-600">{formatCurrency(category.grossProfit)}</span></div><div className="mt-1 text-right text-xs text-muted-foreground">{category.revenue.totalRevenue ? ((category.grossProfit / category.revenue.totalRevenue) * 100).toFixed(1) : '0.0'}% margin</div></div></div></CardContent></Card>)}</div>
    <Card className="bg-muted/50"><CardHeader><CardTitle className="text-lg">Key Insights</CardTitle></CardHeader><CardContent><div className="space-y-2 text-sm"><div className="flex items-start gap-2"><span className="min-w-[120px] font-semibold">Performance:</span><span className={isProfit ? 'text-green-600' : 'text-red-600'}>{isProfit ? `Profitable day with ${report.metrics.netProfitMargin.toFixed(1)}% net margin` : `Loss of ${formatCurrency(Math.abs(report.netProfit))} - review expenses`}</span></div>{bestCategory && <div className="flex items-start gap-2"><span className="min-w-[120px] font-semibold">Best Category:</span><span>{bestCategory.label} ({formatCurrency(bestCategory.grossProfit)} gross profit)</span></div>}<div className="flex items-start gap-2"><span className="min-w-[120px] font-semibold">Orders:</span><span>{report.metrics.orderCount} orders processed</span></div></div></CardContent></Card>
  </div>;
}
