apiVersion: v1
kind: Service
metadata:
  name: wawagardenbar-uat-app
  namespace: apps
  labels:
    app.kubernetes.io/name: wawagardenbar-app
    app.kubernetes.io/instance: uat
    app.kubernetes.io/component: app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wawagardenbar-app
    app.kubernetes.io/instance: uat
    app.kubernetes.io/component: app
  ports:
    - port: 80
      targetPort: 3000
