/**
 * Seed Drinks Menu and Inventory
 * 
 * Populates menu items and inventory from the drinks menu data
 * 
 * Usage: npx tsx scripts/seed-drinks-menu.ts
 */

import { config } from 'dotenv';
const result = config({ path: '.env.local' });
if (result.error && !process.env.MONGODB_WAWAGARDENBAR_APP_URI) {
  console.error('⚠️  Environment variables not set');
  process.exit(1);
}

import { connectDB } from '../lib/mongodb';
import MenuItemModel from '../models/menu-item-model';
import InventoryModel from '../models/inventory-model';

interface DrinkItem {
  name: string;
  description: string;
  mainCategory: string;
  category: string;
  price: number;
  preparationTime: number;
  tags: string[];
  availableForOrdering: boolean;
  inventoryTracking: {
    enabled: boolean;
    initialStock: number;
    unit: string;
    minimumStock: number;
    maximumStock: number;
    costPerUnit: number;
    supplier: string;
    preventOrdersWhenOutOfStock: boolean;
  };
}

const drinksMenu: DrinkItem[] = [
  {
    name: 'Gulder',
    description: 'Premium Nigerian lager with a crisp, refreshing taste. Perfect for unwinding after a long day.',
    mainCategory: 'drinks',
    category: 'beer-local',
    price: 1500,
    preparationTime: 5,
    tags: ['Beer', 'Local', 'Lager'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 120,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 120,
      costPerUnit: 941.667,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: '33',
    description: 'Nigeria\'s classic lager beer with a smooth, balanced flavor. A timeless favorite that pairs perfectly with any meal.',
    mainCategory: 'drinks',
    category: 'beer-local',
    price: 1300,
    preparationTime: 5,
    tags: ['Beer', 'Local', 'Lager'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 120,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 120,
      costPerUnit: 791.667,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Smirnoff Ice - Small',
    description: 'Vodka-based drink with a zesty lemon-lime flavor. Sweet, refreshing, and perfectly carbonated for a smooth taste.',
    mainCategory: 'drinks',
    category: 'pre-mixed-spirit',
    price: 1200,
    preparationTime: 5,
    tags: ['Pre-mix', 'Vodka', 'Citrus'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 60,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 60,
      costPerUnit: 560.417,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Smirnoff Ice - Big',
    description: 'Larger serving of the popular vodka cooler. Crisp citrus flavor with just the right amount of sweetness.',
    mainCategory: 'drinks',
    category: 'pre-mixed-spirit',
    price: 2000,
    preparationTime: 5,
    tags: ['Pre-mix', 'Vodka', 'Citrus'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 60,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 60,
      costPerUnit: 1058.33,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Guinness Small Stout',
    description: 'Rich, creamy stout with bold flavors of roasted malt and coffee. The perfect pick-me-up with its smooth, velvety texture.',
    mainCategory: 'drinks',
    category: 'beer-local',
    price: 1200,
    preparationTime: 5,
    tags: ['Beer', 'Stout', 'Dark'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 120,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 120,
      costPerUnit: 808.333,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Guinness Medium Stout',
    description: 'The iconic extra smooth stout in a satisfying medium size. Full-bodied with notes of chocolate and caramel.',
    mainCategory: 'drinks',
    category: 'beer-local',
    price: 1500,
    preparationTime: 5,
    tags: ['Beer', 'Stout', 'Dark'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 120,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 120,
      costPerUnit: 930.556,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Guinness Big Stout',
    description: 'Extra large serving of Nigeria\'s most beloved stout. Rich, bold, and incredibly smooth - perfect for serious stout lovers.',
    mainCategory: 'drinks',
    category: 'beer-local',
    price: 2000,
    preparationTime: 5,
    tags: ['Beer', 'Stout', 'Dark'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 120,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 120,
      costPerUnit: 1266.67,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Orijin Beer',
    description: 'Unique herbal-infused beer blending traditional African botanicals with modern brewing. A bold, distinctive taste that celebrates Nigerian heritage.',
    mainCategory: 'drinks',
    category: 'beer-local',
    price: 1500,
    preparationTime: 5,
    tags: ['Beer', 'Local', 'Herbal'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 60,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 60,
      costPerUnit: 791.667,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Budweiser',
    description: 'America\'s iconic lager, crisp and refreshing with a smooth finish. The King of Beers, enjoyed worldwide.',
    mainCategory: 'drinks',
    category: 'beer-imported',
    price: 1500,
    preparationTime: 5,
    tags: ['Beer', 'Imported', 'Lager'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 120,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 120,
      costPerUnit: 775,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Flying Fish',
    description: 'Refreshing fruit cider with a perfect blend of sweetness and fizz. Light, fruity, and incredibly easy to drink.',
    mainCategory: 'drinks',
    category: 'cider',
    price: 1500,
    preparationTime: 5,
    tags: ['Cider', 'Fruit', 'Refreshing'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 60,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 60,
      costPerUnit: 625,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Trophy Stout',
    description: 'Dark, robust stout with a rich malty flavor. Smooth and satisfying, perfect for those who appreciate a good Nigerian stout.',
    mainCategory: 'drinks',
    category: 'beer-local',
    price: 1300,
    preparationTime: 5,
    tags: ['Beer', 'Stout', 'Local'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 60,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 60,
      costPerUnit: 762.5,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Trophy',
    description: 'Light, crisp lager with a clean finish. Refreshing and easy to drink, ideal for hot Nigerian afternoons.',
    mainCategory: 'drinks',
    category: 'beer-local',
    price: 1300,
    preparationTime: 5,
    tags: ['Beer', 'Lager', 'Local'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 120,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 120,
      costPerUnit: 708.333,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Goldberg',
    description: 'Premium Nigerian lager with a distinctive golden color and smooth taste. Perfectly balanced for maximum refreshment.',
    mainCategory: 'drinks',
    category: 'beer-local',
    price: 1300,
    preparationTime: 5,
    tags: ['Beer', 'Lager', 'Local'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 120,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 120,
      costPerUnit: 791.667,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Heineken',
    description: 'Premium Dutch lager with a distinctive taste and quality. Crisp, slightly bitter, and incredibly refreshing - a global favorite.',
    mainCategory: 'drinks',
    category: 'beer-imported',
    price: 2000,
    preparationTime: 5,
    tags: ['Beer', 'Imported', 'Premium', 'Lager'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 120,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 120,
      costPerUnit: 1050,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Star Radler',
    description: 'Refreshing lemon-flavored beer with a perfect balance of citrus and malt. Light, fruity, and incredibly refreshing.',
    mainCategory: 'drinks',
    category: 'beer-local',
    price: 1200,
    preparationTime: 5,
    tags: ['Beer', 'Radler', 'Lemon'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 60,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 60,
      costPerUnit: 675,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Desperados',
    description: 'Bold tequila-flavored beer with a unique kick. Adventurous and exciting, perfect for those who like to try something different.',
    mainCategory: 'drinks',
    category: 'beer-imported',
    price: 1500,
    preparationTime: 5,
    tags: ['Beer', 'Imported', 'Tequila'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 140,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 140,
      costPerUnit: 910,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Tiger',
    description: 'Premium Asian lager with a smooth, crisp taste. Refreshing and well-balanced, perfect for any occasion.',
    mainCategory: 'drinks',
    category: 'beer-imported',
    price: 1300,
    preparationTime: 5,
    tags: ['Beer', 'Imported', 'Lager'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 100,
      unit: 'bottles',
      minimumStock: 15,
      maximumStock: 100,
      costPerUnit: 725,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Action Bitters - Small',
    description: 'Traditional Nigerian herbal bitters with medicinal properties. Bold, aromatic, and believed to aid digestion and boost vitality.',
    mainCategory: 'drinks',
    category: 'bitters',
    price: 1500,
    preparationTime: 5,
    tags: ['Bitters', 'Herbal'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 100,
      unit: 'bottles',
      minimumStock: 10,
      maximumStock: 100,
      costPerUnit: 645.833,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Action Bitters - Big',
    description: 'Large bottle of premium herbal bitters. Rich blend of African herbs and spices for health-conscious drinkers.',
    mainCategory: 'drinks',
    category: 'bitters',
    price: 5000,
    preparationTime: 5,
    tags: ['Bitters', 'Herbal'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 6,
      unit: 'bottles',
      minimumStock: 2,
      maximumStock: 6,
      costPerUnit: 2666.67,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Orijin - Small',
    description: 'Herbal bitters infused with African botanicals. Smooth, aromatic, and perfect for those who appreciate traditional Nigerian flavors.',
    mainCategory: 'drinks',
    category: 'bitters',
    price: 1500,
    preparationTime: 5,
    tags: ['Bitters', 'Herbal'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 75,
      unit: 'bottles',
      minimumStock: 10,
      maximumStock: 75,
      costPerUnit: 395.833,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Orijin - Big',
    description: 'Premium large bottle of herbal bitters. Rich, complex flavors from carefully selected African herbs and roots.',
    mainCategory: 'drinks',
    category: 'bitters',
    price: 5000,
    preparationTime: 5,
    tags: ['Bitters', 'Herbal'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 6,
      unit: 'bottles',
      minimumStock: 2,
      maximumStock: 6,
      costPerUnit: 3300,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Cream Best - Small',
    description: 'Smooth, creamy liqueur with a rich, indulgent taste. Perfect for sipping or mixing, with notes of vanilla and caramel.',
    mainCategory: 'drinks',
    category: 'liqueur',
    price: 2500,
    preparationTime: 5,
    tags: ['Liqueur', 'Cream'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 24,
      unit: 'bottles',
      minimumStock: 4,
      maximumStock: 24,
      costPerUnit: 3000,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Cream Best - Big',
    description: 'Large bottle of premium cream liqueur. Luxuriously smooth and perfect for special occasions or sharing with friends.',
    mainCategory: 'drinks',
    category: 'liqueur',
    price: 9000,
    preparationTime: 5,
    tags: ['Liqueur', 'Cream'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 6,
      unit: 'bottles',
      minimumStock: 2,
      maximumStock: 6,
      costPerUnit: 6000,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Black Bullet',
    description: 'Bold pre-mixed spirit drink with an intense flavor. Strong, smooth, and perfect for those who like their drinks with a kick.',
    mainCategory: 'drinks',
    category: 'pre-mixed-spirit',
    price: 3000,
    preparationTime: 5,
    tags: ['Pre-mix', 'Spirit'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 32,
      unit: 'bottles',
      minimumStock: 8,
      maximumStock: 32,
      costPerUnit: 1800,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: '4th Street Wine',
    description: 'Sweet, fruity wine with vibrant flavors. Easy to drink and perfect for celebrations or relaxed evenings.',
    mainCategory: 'drinks',
    category: 'wine',
    price: 7000,
    preparationTime: 5,
    tags: ['Wine', 'Sweet', 'Fruit'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 6,
      unit: 'bottles',
      minimumStock: 2,
      maximumStock: 6,
      costPerUnit: 4700,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Baron',
    description: 'Smooth red wine with rich, full-bodied flavors. Perfect for pairing with meals or enjoying on its own.',
    mainCategory: 'drinks',
    category: 'wine',
    price: 6000,
    preparationTime: 5,
    tags: ['Wine', 'Red'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 6,
      unit: 'bottles',
      minimumStock: 2,
      maximumStock: 6,
      costPerUnit: 4200,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Whiskey Best - Small',
    description: 'Smooth blended whiskey with a mellow taste. Perfect for sipping neat or mixing in your favorite cocktail.',
    mainCategory: 'drinks',
    category: 'whisky',
    price: 3000,
    preparationTime: 5,
    tags: ['Whisky', 'Spirit'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 24,
      unit: 'bottles',
      minimumStock: 2,
      maximumStock: 24,
      costPerUnit: 2000,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Whiskey Best - Big',
    description: 'Large bottle of quality blended whiskey. Smooth, versatile, and perfect for entertaining guests.',
    mainCategory: 'drinks',
    category: 'whisky',
    price: 6000,
    preparationTime: 5,
    tags: ['Whisky', 'Spirit'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 6,
      unit: 'bottles',
      minimumStock: 2,
      maximumStock: 6,
      costPerUnit: 5000,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Sierra Tequila',
    description: 'Premium silver tequila from Mexico. Smooth, clean taste perfect for shots or margaritas. The life of any party!',
    mainCategory: 'drinks',
    category: 'tequila',
    price: 16000,
    preparationTime: 5,
    tags: ['Tequila', 'Spirit', 'Premium'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 6,
      unit: 'bottles',
      minimumStock: 2,
      maximumStock: 6,
      costPerUnit: 10000,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'William Lawson',
    description: 'Premium Scotch whisky with a smooth, refined character. Rich flavors of oak and vanilla for the sophisticated palate.',
    mainCategory: 'drinks',
    category: 'whisky',
    price: 15000,
    preparationTime: 5,
    tags: ['Whisky', 'Scotch', 'Premium'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 6,
      unit: 'bottles',
      minimumStock: 2,
      maximumStock: 6,
      costPerUnit: 24000,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Jameson',
    description: 'World-renowned Irish whiskey, triple-distilled for exceptional smoothness. Rich, complex flavors with hints of vanilla and sherry.',
    mainCategory: 'drinks',
    category: 'whisky',
    price: 35000,
    preparationTime: 5,
    tags: ['Whisky', 'Irish', 'Premium'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 6,
      unit: 'bottles',
      minimumStock: 2,
      maximumStock: 6,
      costPerUnit: 6266.67,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Power Horse',
    description: 'High-energy drink packed with caffeine and vitamins. Boost your energy and stay alert throughout the day.',
    mainCategory: 'drinks',
    category: 'energy-drink',
    price: 3000,
    preparationTime: 5,
    tags: ['Energy-drink', 'Caffeine'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 64,
      unit: 'bottles',
      minimumStock: 4,
      maximumStock: 64,
      costPerUnit: 875,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Super Commando Small',
    description: 'Affordable energy boost in a convenient size. Quick pick-me-up when you need extra energy.',
    mainCategory: 'drinks',
    category: 'energy-drink',
    price: 500,
    preparationTime: 5,
    tags: ['Energy-drink', 'Caffeine'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 60,
      unit: 'bottles',
      minimumStock: 6,
      maximumStock: 60,
      costPerUnit: 266.667,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Fearless',
    description: 'Bold energy drink with a powerful kick. Stay energized and focused with this refreshing boost.',
    mainCategory: 'drinks',
    category: 'energy-drink',
    price: 1000,
    preparationTime: 5,
    tags: ['Energy-drink', 'Caffeine'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 60,
      unit: 'bottles',
      minimumStock: 6,
      maximumStock: 60,
      costPerUnit: 416.667,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: '5 Alive (Pulpy)',
    description: 'Real fruit juice with juicy orange pulp. Refreshing, nutritious, and bursting with natural citrus flavor.',
    mainCategory: 'drinks',
    category: 'juice',
    price: 1500,
    preparationTime: 5,
    tags: ['Juice', 'Orange', 'Pulpy'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 30,
      unit: 'bottles',
      minimumStock: 6,
      maximumStock: 30,
      costPerUnit: 1000,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Chi Active',
    description: 'Nutritious fruit juice drink packed with vitamins. Healthy, delicious, and perfect for active lifestyles.',
    mainCategory: 'drinks',
    category: 'juice',
    price: 2500,
    preparationTime: 5,
    tags: ['Juice', 'Fruit'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 30,
      unit: 'Carton',
      minimumStock: 3,
      maximumStock: 30,
      costPerUnit: 1500,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Hollandia Plain',
    description: 'Smooth, creamy plain yoghurt. Rich in probiotics, perfect for a healthy snack or breakfast addition.',
    mainCategory: 'drinks',
    category: 'yoghurt',
    price: 2500,
    preparationTime: 5,
    tags: ['Yoghurt', 'Dairy'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 30,
      unit: 'Carton',
      minimumStock: 4,
      maximumStock: 30,
      costPerUnit: 1580,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Hollandia Vanilla',
    description: 'Delicious vanilla-flavored yoghurt. Creamy, sweet, and packed with nutrients for a healthy treat.',
    mainCategory: 'drinks',
    category: 'yoghurt',
    price: 2500,
    preparationTime: 5,
    tags: ['Yoghurt', 'Dairy', 'Vanilla'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 30,
      unit: 'Carton',
      minimumStock: 4,
      maximumStock: 30,
      costPerUnit: 1580,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Maltina',
    description: 'Non-alcoholic malt drink with a rich, distinctive flavor. Nutritious and refreshing, perfect for all ages.',
    mainCategory: 'drinks',
    category: 'malt',
    price: 1000,
    preparationTime: 5,
    tags: ['Malt', 'Non-alcoholic'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 60,
      unit: 'bottles',
      minimumStock: 6,
      maximumStock: 60,
      costPerUnit: 433.333,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Coke',
    description: 'The world\'s favorite cola. Crisp, refreshing, and perfectly carbonated. A timeless classic.',
    mainCategory: 'drinks',
    category: 'soft-drinks',
    price: 700,
    preparationTime: 5,
    tags: ['Soft-drink', 'Cola'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 60,
      unit: 'bottles',
      minimumStock: 6,
      maximumStock: 60,
      costPerUnit: 375,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Pepsi',
    description: 'Bold cola taste with a refreshing finish. Smooth, sweet, and incredibly satisfying.',
    mainCategory: 'drinks',
    category: 'soft-drinks',
    price: 700,
    preparationTime: 5,
    tags: ['Soft-drink', 'Cola'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 60,
      unit: 'bottles',
      minimumStock: 6,
      maximumStock: 60,
      costPerUnit: 375,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Fanta',
    description: 'Bright, fruity orange soda bursting with citrus flavor. Fun, refreshing, and perfect for any occasion.',
    mainCategory: 'drinks',
    category: 'soft-drinks',
    price: 700,
    preparationTime: 5,
    tags: ['Soft-drink', 'Orange'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 60,
      unit: 'bottles',
      minimumStock: 6,
      maximumStock: 60,
      costPerUnit: 375,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'Zobo',
    description: 'Traditional Nigerian hibiscus drink. Naturally sweet, tangy, and packed with antioxidants. A healthy, refreshing choice.',
    mainCategory: 'drinks',
    category: 'healthy-soft-drink',
    price: 1000,
    preparationTime: 5,
    tags: ['Soft-drink', 'Healthy', 'Traditional'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 10,
      unit: 'bottles',
      minimumStock: 2,
      maximumStock: 10,
      costPerUnit: 125,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
  {
    name: 'C-Water',
    description: 'Pure, refreshing bottled water. Stay hydrated with clean, crisp water perfect for any time of day.',
    mainCategory: 'drinks',
    category: 'water',
    price: 300,
    preparationTime: 5,
    tags: ['Water', 'Bottled'],
    availableForOrdering: true,
    inventoryTracking: {
      enabled: true,
      initialStock: 120,
      unit: 'bottles',
      minimumStock: 24,
      maximumStock: 120,
      costPerUnit: 125,
      supplier: '',
      preventOrdersWhenOutOfStock: true,
    },
  },
];

async function seedDrinksMenu() {
  try {
    console.log('\n🍺 Seeding Drinks Menu and Inventory\n');

    await connectDB();
    console.log('✅ Connected to database\n');

    // Optional: Clear existing drinks (uncomment if needed)
    // console.log('🗑️  Clearing existing drinks...');
    // await MenuItemModel.deleteMany({ mainCategory: 'Drinks' });
    // await InventoryModel.deleteMany({});
    // console.log('✅ Cleared existing drinks\n');

    console.log(`📦 Creating ${drinksMenu.length} drink items...\n`);

    let menuCreated = 0;
    let inventoryCreated = 0;

    for (const drink of drinksMenu) {
      // Create menu item first (without inventory link)
      const menuItem = await MenuItemModel.create({
        name: drink.name,
        description: drink.description,
        mainCategory: drink.mainCategory,
        category: drink.category,
        price: drink.price,
        costPerUnit: drink.inventoryTracking.costPerUnit,
        preparationTime: drink.preparationTime,
        servingSize: '1 bottle',
        tags: drink.tags,
        isAvailable: drink.availableForOrdering,
        displayPriority: 0,
        trackInventory: drink.inventoryTracking.enabled,
      });

      menuCreated++;
      console.log(`✅ Created menu item: ${drink.name} (₦${drink.price.toLocaleString()})`);

      // Create inventory if tracking is enabled
      if (drink.inventoryTracking.enabled) {
        const inventory = await InventoryModel.create({
          menuItemId: menuItem._id,
          menuItemName: drink.name,
          currentStock: drink.inventoryTracking.initialStock,
          minimumStock: drink.inventoryTracking.minimumStock,
          maximumStock: drink.inventoryTracking.maximumStock,
          unit: drink.inventoryTracking.unit,
          costPerUnit: drink.inventoryTracking.costPerUnit,
          supplier: drink.inventoryTracking.supplier || 'Not specified',
          preventOrdersWhenOutOfStock: drink.inventoryTracking.preventOrdersWhenOutOfStock,
        });

        // Link inventory back to menu item
        menuItem.inventoryId = inventory._id.toString();
        await menuItem.save();

        inventoryCreated++;
        console.log(`   📊 Created inventory: ${drink.inventoryTracking.initialStock} ${drink.inventoryTracking.unit}`);
        console.log(`   🔗 Linked inventory to menu item\n`);
      }
    }

    console.log('\n✅ Seeding complete!\n');
    console.log('📊 Summary:');
    console.log(`   Menu items created: ${menuCreated}`);
    console.log(`   Inventory records created: ${inventoryCreated}`);
    console.log(`   Total drinks: ${drinksMenu.length}\n`);

    // Category breakdown
    const categories = drinksMenu.reduce((acc, drink) => {
      acc[drink.category] = (acc[drink.category] || 0) + 1;
      return acc;
    }, {} as Record<string, number>);

    console.log('📋 Category Breakdown:');
    Object.entries(categories)
      .sort((a, b) => b[1] - a[1])
      .forEach(([category, count]) => {
        console.log(`   ${category}: ${count} items`);
      });

    console.log('\n');

    process.exit(0);
  } catch (error) {
    console.error('\n❌ Error seeding drinks menu:', error);
    process.exit(1);
  }
}

seedDrinksMenu();
